# -*- coding: utf-8 -*-
"""1018.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/147UXwFEBiPRTVp1UJWZ-WHtpC1BnKfmz
"""

n = int(input())
print(n)
if 0 < n < 1000000:
  c100 = n // 100
  n = n - c100 * 100

  c50 = n // 50
  n = n - c50 * 50

  c20 = n // 20
  n = n - c20 * 20

  c10 = n // 10
  n = n - c10 * 10

  c5 = n // 5
  n = n - c5 * 5

  c2 = n // 2
  n = n - c2 * 2

  c1 = n // 1
  n = n - c1 * 1
  print('{} nota(s) de R$ 100,00'.format(c100))
  print('{} nota(s) de R$ 50,00'.format(c50))
  print('{} nota(s) de R$ 20,00'.format(c20))
  print('{} nota(s) de R$ 10,00'.format(c10))
  print('{} nota(s) de R$ 5,00'.format(c5))
  print('{} nota(s) de R$ 2,00'.format(c2))
  print('{} nota(s) de R$ 1,00'.format(c1))