# -*- coding: utf-8 -*-
"""1020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16RpQPEyT1A_AYH5bt29QvBv0ARuKMSmw
"""

idade = int(input())

ano = idade // 365
idade = idade - ano * 365

mes = idade // 30
idade = idade - mes * 30

dias = idade

print('{} ano(s)'.format(ano))
print('{} mes(es)'.format(mes))
print('{} dia(s)'.format(dias))