# -*- coding: utf-8 -*-
"""1036.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s7WG18HECrHvuhACz3JNfEsCItvk9VU4
"""

a, b, c = input().split()
a = float(a)
b = float(b)
c = float(c)

if a == 0 or (b ** 2 - 4 * a * c) < 0:
  print('Impossivel calcular')
else:
    r1 = (- b + (b ** 2 - 4 * a * c) ** 0.5) / (2 * a)
    r2 = (- b - (b ** 2 - 4 * a * c) ** 0.5) / (2 * a)
    print('R1 = %.5f' % r1)
    print('R2 = %.5f' % r2)