# -*- coding: utf-8 -*-
"""1037.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dWg8kLSAIqLR2qCcjTvmTSkbzVqjlPMW
"""

a = float(input())

if a < 0 or a > 100:
  print('Fora de intervalo')
if 0 <= a <= 25:
  print('Intervalo [0,25]')
if 25 < a <= 50:
  print('Intervalo (25,50]')
if 50 < a <= 75:
  print('Intervalo (50,75]')
if 75 < a <= 100:
  print('Intervalo (75,100]')