# -*- coding: utf-8 -*-
"""1038.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yz_RS9PZTe7-cWCiDRZ70tQqq76FksRr
"""

a, b = input().split()
a = int(a)
b = int(b)
total = float()

if a == 1:
  total = 4.00 * b
if a == 2:
  total = 4.50 * b
if a == 3:
  total = 5.00 * b
if a == 4:
  total = 2.00 * b
if a == 5:
  total = 1.50 * b

print('Total: R$ %.2f' %total)