# -*- coding: utf-8 -*-
"""1040.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_hLdRlWQyEz7gMbLGx4Gb3wmSWL0hUSQ
"""

n1,n2, n3, n4 = input().split()
n1 = float(n1)
n2 = float(n2)
n3 = float(n3)
n4 = float(n4)
media = (n1 * 2.0 + n2 * 3.0 + n3 * 4.0 + n4 * 1.0) / 10.0

print('Media: %.1f' %media)
if media >= 7.0:
  print('Aluno aprovado.')
if media < 5.0:
  print('Aluno reprovado.')
if 5.0 <= media <= 6.9:
  print('Aluno em exame.')
  exame = float(input())
  print('Nota do exame: %.1f' %exame)
  media_final = ((exame + media) / 2.0)
  if media_final >= 5.0:
    print('Aluno aprovado.')
    print('Media final: %.1f' %media_final)
  else:
    print('Aluno reprovado.')
    print('Media final: %.1f' %media_final)