# -*- coding: utf-8 -*-
"""1043.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TdnRY0ZG2S3ykIdxD13BbrhHO8Uk8ta0
"""

a, b, c = input().split()
a = float(a)
b = float(b)
c = float(c)

if a + b > c and a + c > b and b + c > a:
  p = a + b + c
  print('Perimetro = %.1f' %p)
else:
  area_trapezio = ((a + b) * c) / 2
  print('Area = %.1f' %area_trapezio)