# -*- coding: utf-8 -*-
"""1044.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KXlyZyKmwIBbQeAcWNwE0AJ1rxXui1Hh
"""

a, b = input().split()
a = int(a)
b = int(b)

if a % b == 0 or b % a == 0:
  print('Sao Multiplos')
else:
  print('Nao sao Multiplos')