# -*- coding: utf-8 -*-
"""1045.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K6FIVdAghr-9IHkFx0vSjmGpQ5UbAXI-
"""

l1, l2, l3 = input().split()
l1 = float(l1)
l2 = float(l2)
l3 = float(l3)

if l1 >= l2 and l1 >= l3:
  A = l1 
  if l2 >= l3:
    B = l2
    C = l3
  else:
    B = l3
    C = l2

if l2 >= l1 and l2 >= l3:
  A = l2 
  if l1 >= l3:
    B = l1
    C = l3
  else:
    B = l3
    C = l1

if l3 >= l2 and l3 >= l1:
  A = l3 
  if l2 >= l1:
    B = l2
    C = l1
  else:
    B = l1
    C = l2

if A >= (B + C):
  print('NAO FORMA TRIANGULO')
elif A == B and B == C:
  print('TRIANGULO ACUTANGULO')
  print('TRIANGULO EQUILATERO')
elif A == B or A == C or B == C:
  if A ** 2 == B ** 2 + C ** 2:
    print('TRIANGULO RETANGULO')
    print('TRIANGULO ISOSCELES')
  if A ** 2 > B ** 2 + C ** 2:
    print('TRIANGULO OBTUSANGULO')
    print('TRIANGULO ISOSCELES')
  if A ** 2 < B ** 2 + C ** 2:
    print('TRIANGULO ACUTANGULO')
    print('TRIANGULO ISOSCELES')
else:
  if A ** 2 == B ** 2 + C ** 2:
    print('TRIANGULO RETANGULO')
  if A ** 2 > B ** 2 + C ** 2:
    print('TRIANGULO OBTUSANGULO')
  if A ** 2 < B ** 2 + C ** 2:
    print('TRIANGULO ACUTANGULO')