# -*- coding: utf-8 -*-
"""1046.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gkJzuvDcBRUiCTSwKKl_-6bqkUbFUFjA
"""

hi, hf = input().split()
hi = int(hi)
hf = int(hf)

if hi < hf:
    t = hf - hi
else:
    t = (24 - hi) + hf
print('O JOGO DUROU {} HORA(S)'.format(t))