# -*- coding: utf-8 -*-
"""1048.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IADtsKjRRv_2XnF-q_9YcR10-YKgUtNC
"""



s = float(input())

if s <= 400.00:
  p = 15
  r = s * 0.15
  ns = s * 1.15
if 400.01 <= s <= 800.00:
  p = 12
  r = s * 0.12
  ns = s * 1.12
if 800.01 <= s <= 1200.00:
  p = 10
  r = s * 0.1
  ns = s * 1.1
if 1200.01 <= s <= 2000.00:
  p = 7
  r = s * 0.07
  ns = s * 1.07
if s > 2000.00:
  p = 4
  r = s * 0.04
  ns = s * 1.04

print('Novo salario: {:.2f}'.format(ns))
print('Reajuste ganho: {:.2f}'.format(r))
print('Em percentual: {} %'.format(p))