# -*- coding: utf-8 -*-
"""1049.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13PZNTqEr8F02O6e0mDPuI8aT5wO0BS-V
"""

x = input()
y = input()
z = input()

if x == 'vertebrado':
  if y == 'ave':
    if z == 'carnivoro':
      a = 'aguia'
    else:
      a = 'pomba'
  elif z == 'onivoro':
    a = 'homem'
  else:
    a = 'vaca'
else:
  if y == 'inseto':
    if z == 'hematofago':
      a = 'pulga'
    else:
      a = 'lagarta'
  elif z == 'hematofago':
    a = 'sanguessuga'
  else:
    a = 'minhoca'
     
print(a)