# -*- coding: utf-8 -*-
"""1050.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nuq8KIqBBR0wwBKaS2CzYMSgcfoPXKlR
"""

ddd = int(input())

if ddd == 61:
  print('Brasilia')
elif ddd == 71:
  print('Salvador')
elif ddd == 11:
  print('Sao Paulo')
elif ddd == 21:
  print('Rio de Janeiro')
elif ddd == 32:
  print('Juiz de Fora')
elif ddd == 19:
  print('Campinas')
elif ddd == 27:
  print('Vitoria')
elif ddd == 31:
  print('Belo Horizonte')
else:
  print('DDD nao cadastrado')