# -*- coding: utf-8 -*-
"""1051.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12wc0B0PFy405q98mCArVehQL5YWFnslO
"""

renda = float(input())

if renda <= 2000.00:
  print('Isento')

if 2000.01 <= renda <= 3000.00:
  i = (renda - 2000.00) * 0.08

if 3000.01 <= renda <= 4500.00:
  i = (renda - 3000.00) * 0.18 + (0.08 * 1000.00)

if renda > 4500.00:
  i = (renda - 4500.00) * 0.28 + (0.08 * 1000.00) + (0.18 * 1500.00)

if renda > 2000.00:
  print('R$ %.2f' % i)