# -*- coding: utf-8 -*-
"""1059.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hX_TLg0il2vBPpN4GL9vsSmrmjGFpjRg
"""

for x in range (1, 101):
  if x % 2 == 0:
    print(x)