# -*- coding: utf-8 -*-
"""1060.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zNcVGP4uENbU48cqN9hJ7e2aIsRprpW9
"""

i = 0
for x in range(1,7):
  a = float(input())
  if a > 0:
    i = i + 1

print('{} valores positivos'.format(i))