# -*- coding: utf-8 -*-
"""1061.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1II8mhcQjcgTR2c1CJnBvw5K0jTXUGGCf
"""

dia_inicial = input().split()
hora_inicial = input().split()
dia_final = input().split()
hora_final = input().split()

di, df = int(dia_inicial[1]), int(dia_final[1])
hi, mi, si = int(hora_inicial[0]), int(hora_inicial[2]), int(hora_inicial[4])
hf, mf, sf = int(hora_final[0]), int(hora_final[2]), int(hora_final[4])

i = si + mi * 60 + hi * 3600 + di * 86400
f = sf + mf * 60 + hf * 3600 + df * 86400

tempo = f - i
dias = int(tempo//86400)
tempo = tempo%86400
horas = int(tempo//3600)
tempo = tempo%3600
minutos = int(tempo//60)
tempo = tempo%60
segundos = tempo

print('{} dia(s)'.format(dias))
print('{} hora(s)'.format(horas))
print('{} minuto(s)'.format(minutos))
print('{} segundo(s)'.format(segundos))