# -*- coding: utf-8 -*-
"""1064.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16m4Yl6GIIak39cfOeyyuQ-md1GOaa79n
"""

a = float(input())
b = float(input())
c = float(input())
d = float(input())
e = float(input())
f = float(input())

s = 0
m = 0

if a > 0:
  s = s + 1
  m = m + a

if b > 0:
  s = s + 1
  m = m + b

if c > 0:
  s = s + 1
  m = m + c

if d > 0:
  s = s + 1
  m = m + d

if e > 0:
  s = s + 1
  m = m + e

if f > 0:
  s = s + 1
  m = m + f

media = m / s
print('{} valores positivos'.format(s))
print('{:.1f}'.format(media))