# -*- coding: utf-8 -*-
"""1074.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QJKTrWFk9pJKPoD3XvgZYdKevAdOtCIz
"""

N = int(input())
while N > 0:
  a = int(input())
  if a == 0:
    print('NULL')
  elif a > 0:
    if a % 2 == 0:
      print('EVEN POSITIVE')
    else:
      print('ODD POSITIVE')
  else:
    if a % 2 == 0:
      print('EVEN NEGATIVE')
    else:
      print('ODD NEGATIVE')
  N = N - 1