# -*- coding: utf-8 -*-
"""1079.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mm2bCFFP8qRiM9OgY46tOhTBL-eWTDU-
"""

N = int(input())
while N > 0:
  x = input().split()
  a = float(x[0])
  b = float(x[1])
  c = float(x[2])
  M = (a * 2 + b * 3 + c * 5) / 10
  N = N - 1
  print('{:.1f}'.format(M))