# -*- coding: utf-8 -*-
"""1080v.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nwplzfvU51OJZb26gs_sBs5eHZUeAzRy
"""

v = list(range(100))
pos = 0
maior = 0

for i in range(100):
  v[i] = int(input())
  if v[i] > maior:
    maior = v[i]
    posicao = i + 1
  
print(maior)
print(posicao)