# -*- coding: utf-8 -*-
"""1080.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LEQwhM-D8mHYDz9tbQwerHsIAanbfZ-O
"""

n = 100
pos = 0
cont = 1
maior = 0
while n > 0:
  i = int(input())
  n = n - 1
  if i > maior:
    maior = i
    pos = cont
  cont = cont + 1
print(maior)
print(pos)