# -*- coding: utf-8 -*-
"""1094.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lDz0RfYQOABnmWcWYNMlPp7HrjwMAdoC
"""

N = int(input())
total = 0
coelho = 0
rato = 0
sapo = 0

while N > 0:
  x = input().split()
  quantia = int(x[0])
  tipo = str(x[1])
  if tipo == 'C':
      coelho = coelho + quantia
  if tipo == 'R':
      rato = rato + quantia
  if tipo == 'S':
      sapo = sapo + quantia
  
  total = total + quantia
  N = N - 1

print('Total: {} cobaias'.format(total))
print('Total de coelhos: {}'.format(coelho))
print('Total de ratos: {}'.format(rato))
print('Total de sapos: {}'.format(sapo))
print('Percentual de coelhos: {:.2f} %'.format((coelho / total * 100)))
print('Percentual de ratos: {:.2f} %'.format((rato / total * 100)))
print('Percentual de sapos: {:.2f} %'.format((sapo / total * 100)))