# -*- coding: utf-8 -*-
"""1095.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RZszBoKNB_VhjbwugJ7wzAvrGjXeRwC3
"""

I = 1
J = 60

while J >= 0:
  print('I={} J={}'.format(I, J))
  J = J - 5
  I = I + 3