# -*- coding: utf-8 -*-
"""1096.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T5k1uP9B7MbcVyKZMTKArelAE0bK_7wq
"""

I = 1
J = 7

while I < 10:
  while J >= 5:
    print('I={} J={}'.format(I, J))
    J = J - 1
  J = 7
  I = I + 2