# -*- coding: utf-8 -*-
"""1134.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x_FhFMEWD6SK8oV7mGYrgCXfM2AlMLeJ
"""

v = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
i = 0

while i != 4:
  v[i] = v[i] + 1
  i = int(input())
  
print('MUITO OBRIGADO')
print('Alcool: {}'.format(v[1]))
print('Gasolina: {}'.format(v[2]))
print('Diesel: {}'.format(v[3]))