# -*- coding: utf-8 -*-
"""1144.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KzZOolr055YBliZaeZdysjbLxxr-gVXH
"""

N = int(input())
N = N * 2
i = 1
while N > 0:
  print('{} {} {}'.format(i, i * i, i * i * i))
  print('{} {} {}'.format(i, i * i + 1, i * i * i + 1))
  i = i + 1
  N = N - 2