# -*- coding: utf-8 -*-
"""1174.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hrzW_dU0YcQtS3JIK2e4VV29annZmQ5w
"""

v = list(range(100))

for i in range(100):
  n = float(input())
  v[i] = n
  if n <= 10:
    print('A[{}] = {}'.format(i, v[i]))