# -*- coding: utf-8 -*-
"""1175.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17izpo7kCDbMs5GwWFHCtChLQYFnHH5ib
"""

N = list(range(20))

for i in range(20):
  N[i] = int(input())

i = 19
for j in range(20):
  print('N[{}] = {}'.format(j, N[i])) 
  i = i - 1