# -*- coding: utf-8 -*-
"""1176.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Mb1bEFZLk-W_5niWxriulkspjzk2LV6
"""

v = [0, 1]

T = int(input())
for i in range(T):
  N = int(input())
  if N <= 1:
    print('Fib({}) = {}'.format(N,v[N]))
  if N > 1:
    for j in range(2,N+1):
      v[j] = (v[j-1] + v[j-2])
    print('Fib({}) = {}'.format(N, v[N]))