# -*- coding: utf-8 -*-
"""1177.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BSdh8I6J4bNd4lkAAVizzH7gxxrWGhkl
"""

N = [None] * 1000
T = int(input())

j = 0
for i in range(1000):
  N[i] = j
  print('N[{}]: {}'.format(i, j))
  if j < (T - 1):
    j = j + 1
  else:
    j == T - 1
    j = 0