# -*- coding: utf-8 -*-
"""1180.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pul7I1AqgXAnw8djUhDQS4p3tza7_wWh
"""

N = int(input())
x = input().split()

for j in range(len(x)):
  x[j] = int(x[j])
  
menor = x[0]
pos = 0
for j in range(1,len(x)):
  if x[j] < menor:
    menor = x[j]
    pos = j

print('Menor valor: {}'.format(menor))
print('Posicao: {}'.format(pos))