# -*- coding: utf-8 -*-
"""1181.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Nw-xnC6u0jMPEHrz2aOE5-Qq_R_7Ap5
"""

def matriz(lins, cols, val_inic):
     m = [[val_inic] * cols for _ in range(lins)]
     return m

M = matriz(12,12,0.0)
L = int(input())
T = str(input())

for i in range(12):
  for j in range(12):
    M[i][j] = float(input())

soma = 0.0
media = 0.0
i = L
for j in range(12):
  soma = soma + M[i][j]
if T == 'S':
  print('{:.1f}'.format(soma))
if T == 'M':
  media = soma / 12
  print('{:.1f}'.format(media))