# -*- coding: utf-8 -*-
"""1182.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nhlJMKnZxTOom_0ddANU5pbmuyS6VY15
"""

def matriz(lins, cols, val_inic):
     m = [[val_inic] * cols for _ in range(lins)]
     return m

M = matriz(12,12,0.0)
C = int(input())
T = str(input())

for i in range(12):
  for j in range(12):
    M[i][j] = float(input())

soma = 0.0
media = 0.0
j = C
for i in range(12):
  soma = soma + M[i][j]
if T == 'S':
  print('{:.1f}'.format(soma))
if T == 'M':
  media = soma / 12
  print('{:.1f}'.format(media))